config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :celineversions do
    resources :bookings, only: [:show, :new, :create]
  end
  resources :bookings, only: [:index, :update]
  resources :my_celineversions, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :celineversion
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/celineversion.rb
class Celineversion < ApplicationRecord
  include PgSearch::Model
  include AlgoliaSearch

  belongs_to :user
  has_many :bookings, dependent: :destroy

  # add the AlgoliaSearch method
  algoliasearch do
    attributes :name, :description
  end

  # add the pg_search for the advanced search bar
  pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ],
  using: {
    tsearch: { prefix: true }
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :celineversions
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def full_name
    name = first_name.capitalize + " " + last_name.capitalize
    return name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @celineversion = Celineversion.find(params[:celineversion_id])
    @booking = Booking.new
  end

  def create
    @celineversion = Celineversion.find(params[:celineversion_id])
    @user = current_user
    @booking = Booking.new(booking_params)
    @booking.celineversion = @celineversion
    @booking.user = @user
    if @booking.save
      redirect_to bookings_path
    else
      render 'new'
    end
  end


  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to my_celineversions_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/celineversions_controller.rb
class CelineversionsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @celineversions = Celineversion.where(sql_query, query: "%#{params[:query]}%")
    else
      @celineversions = Celineversion.all
    end
  end

  def show
    @celineversion = Celineversion.find(params[:id])
  end

  def new
    @celineversion = Celineversion.new
  end

  def create
    @user = current_user
    @celineversion = Celineversion.new(celineversion_params)
    @celineversion.user = @user
    if @celineversion.save
      redirect_to my_celineversions_path
    else
      render 'new'
    end
  end

  def edit
    @celineversion = Celineversion.find(params[:id])
  end

  def update
    @celineversion = Celineversion.find(params[:id])
    @celineversion.update(celineversion_params)

    redirect_to celineversion_path(@celineversion)
  end

  def destroy
    @celineversion = Celineversion.find(params[:id])
    @celineversion.destroy

    redirect_to my_celineversions_path
  end

  private

  def celineversion_params
    params.require(:celineversion).permit(:name, :description, :price, :image)
  end
end

app/controllers/my_celineversions_controller.rb
class MyCelineversionsController < ApplicationController
  def index
    @celineversions = current_user.celineversions
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar, :photo_cache)
  end
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :avatar, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container my-5">
  <div class="row mt-3">
      <% if @bookings.exists? %>
        <div class="d-flex mt-4">
          <%= image_tag current_user.avatar, class: "avatar-profile mr-3" %>
          <div class="text-left">
            <h2><strong><%= current_user.first_name.capitalize %></strong>'s Booked CélineVersions.</h2>
            <h5>Check all your upcoming bookings and each booking status.</h5>
          </div>
        </div>
        <% @bookings.each do |t| %>
          <div class="col-md-6">
            <div class="card-container mt-4 mb-4">
              <p class="p-2"><strong>Booking ID #<%= t.id %></strong></p>
              <h4 class="p-2 border-top">You booked <strong><%= t.celineversion.name.upcase %></strong></h4>
              <%= image_tag t.celineversion.image, width: 300%>
              <div class="card-container-cont">
                <ul class="card-list">
                  <li><p>You booked this version starting the: <b><%= t.start_date %></b></p></li>
                  <li><p>Your booking will end on: <b><%= t.end_date %></b></p></li>
                  <li><p class="mt-3">Booking Price : <b><%= t.celineversion.price %> $CAD/day</b></p></li>
                  <li><h4 class="mt-3">Current Booking Status : <b><%= t.status.upcase %></b></h4></li>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="d-flex mt-4">
          <%= image_tag current_user.avatar, class: "avatar-profile mr-3" %>
            <div class="text-left">
              <h2><strong><%= current_user.first_name.capitalize %></strong>'s Booked CélineVersions.</h2>
              <h5>You have no upcoming bookings for the moment.</h5>
            </div>
        </div>
    </div>
    <div class="row mt-5">
      <div class="col-md-6">
      <p>List all the available CelineVersions. We know you'll find your joy!</p>
      <%= link_to "Display All CélineVersions", celineversions_path, { class: "btn btn-dark" } %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container my-5">
    <h1 class="mt-5">Book a <b><%= @celineversion.name %></b></h1>
    <h5 class="mb-2">This version's price is <strong><%= @celineversion.price %> $CAD</strong> /day.</h5>
    <!-- <p class="mb-4"><strong><%#= @celineversion.name %></strong> -->
      <%# if @celineversion.bookings.last.status == "Pending" %>
         <!-- is currently<strong> available.</strong> You can book it. -->
      <%# else %>
        <!-- has a booking confirmed from <strong><%#= @celineversion.bookings.last.start_date %></strong> until <strong><%#= @celineversion.bookings.last.end_date %></strong> -->
      <%# end %>
    </p>
  <div class="row">
    <div class="col-md-12">
      <div class="card-form">
      <img src="https://tce-live2.s3.amazonaws.com/media/media/1b80f269-21dc-46fa-80a7-b38d6ff2f388.jpg" />
        <div class="card-form-display">
          <%= simple_form_for([@celineversion, @booking]) do |f| %>
            <%= f.input :message, as: :text, placeholder: "Please write your message here", label: "Write a message for the version's owner" %>
            <%= f.input :start_date, as: :date, html5: true, label: "Start booking on", wrapper_html: { class: "inline_field_wrapper" } %>
            <%= f.input :end_date, as: :date, html5: true, label: 'Booked until'.html_safe, wrapper_html: { class: "inline_field_wrapper" } %>
            <%= f.submit "Book", class: "btn btn-outline-dark"%>
          <% end %>
        </div>
      </div>
      <div class="mt-5 text-right"><%= link_to "BACK TO ALL VERSIONS", celineversions_path, class: "btn btn-light active" %></div>
    </div>
  </div>
</div>

app/views/celineversions/edit.html.erb
<div class="container my-5">
  <h1 class="mt-5">Editing this version > <strong><%= @celineversion.name %></strong></h1>
  <h5 class="mb-4">Want to improve your beloved Diva? Yes, you can.</h5>
  <div class="row">
    <div class="col-md-12">
      <div class="card-form">
        <img src="https://france3-regions.francetvinfo.fr/bretagne/sites/regions_france3/files/styles/top_big/public/assets/images/2019/10/09/maxpaimages658694-4461971.jpg?itok=msyb1q_-" />
          <div class="card-form-display">
            <%= simple_form_for([@user, @celineversion]) do |f| %>
              <%= f.input :name, as: :string, placeholder: "Choose a new name for your version", label: "A new name?" %>
              <%= f.input :description, as: :text, placeholder: "Edit the description of your version", label: "A better description?" %>
              <%= f.input :price, as: :integer, placeholder: "Choose a new price in $CAD for your CélineVersion", label: "A million $CAD version, maybe?" %>
              <%= f.input :image, as: :string, placeholder: "Paste a new url of the image your CélineVersion", label: "Have a better picture?" %>
              <%= f.submit "Update", class: "btn btn-outline-success"%>
            <% end %>
          </div>
      </div>
      <div class="mt-5 text-right"><%= link_to "GO BACK", :back, class: "btn btn-light active" %></div>
    </div>
  </div>
</div>

app/views/celineversions/index.html.erb
<div class="container my-5">

    <h2><strong>All the available CélineVersions</strong></h2>
    <h5 class="mb-5">Choose the version of Céline that fits your style.</h5>

  <div class="row">
    <% @celineversions.each do |t| %>
      <div class="col-md-4">

        <div class="card-container cc-hover mb-4">
          <%= image_tag t.image, width: 300 %>
          <div class="card-container-infos">
            <h2 class="text-left"><%= t.name  %></h2>
            <h4 class="mt-3 text-justify"><%= t.description %></h4>
              <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
          </div>

          <div class="text-center mb-4">
            <h4 class="mb-2"><strong><%= t.price %> $CAD/day</strong></h4>
            <%= link_to "CHECK THIS VERSION", celineversion_path(t), { class: "btn btn-outline-dark font-weight-bold" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/celineversions/index_backup.html.erb
<div class="container my-5">

  <h2><strong>All the available CélineVersions</strong></h2>
  <h5 class="mb-5">Choose the version of Céline that fits your style.</h5>

  <!-- Seach bar start -->
  <div class="search_form">

    <%= form_tag celineversions_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search_bar",
        placeholder: "find a celineversion"
      %>

      <%= submit_tag "Search", class: "btn btn-outline-dark search_btn" %>
    <% end %>
  </div>
  <!-- Seach bar end -->

  <div class="row">
    <% @celineversions.each do |t| %>
      <div class="col-md-4">

        <div class="card-container cc-hover mb-4">
          <%= image_tag t.image, width: 300 %>
          <div class="card-container-infos">
            <h2 class="text-left"><%= t.name  %></h2>
            <h4 class="mt-3 text-justify"><%= t.description %></h4>
              <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
          </div>

          <div class="text-center mb-4">
            <h4 class="mb-2"><strong><%= t.price %> $CAD/day</strong></h4>
            <%= link_to "CHECK THIS VERSION", celineversion_path(t), { class: "btn btn-outline-dark font-weight-bold" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/celineversions/new.html.erb
<div class="container my-5">
  <h1 class="mt-5">Create a new <strong>CélineVersion</strong></h1>
  <h5 class="mb-4">A CélineVersion is missing? It's time to create it!</h5>

  <div class="row">
    <div class="col-md-12">
      <div class="card-form">
        <div class="card-form-display">
          <%= simple_form_for([@user, @celineversion]) do |f| %>
            <%= f.input :name, as: :string, placeholder: "Please choose a name for your version", label: "What's the name of your CélineVersion?" %>
            <%= f.input :description, as: :text, placeholder: "Write down a description of your beloved version of Céline", label: "Describe in few expressive words your beloved CélineVersion" %>
            <%= f.input :price, as: :integer, placeholder: "0000", label: 'Choose a price in $CAD/day for your CélineVersion' %>
            <%= f.input :image, as: :string, placeholder: "Paste the url of the image of your CélineVersion", label: "Choose a nice image for your CélineVersion" %>
            <%= f.submit "Create", class: "btn btn-outline-dark"%>
          <% end %>
        </div>
      <img src="https://i0.gmx.at/image/190/33783190,pd=1,f=opengraph/celine-dion.jpg" />
      </div>
      <div class="mt-5 text-right"><%= link_to "GO TO YOUR CREATED VERSIONS", my_celineversions_path, class: "btn btn-light active" %></div>
    </div>
  </div>

</div>

app/views/celineversions/show.html.erb
<div class="container my-5">
  <h2 class="mb-3">Selected Version > <strong><%= @celineversion.name %></strong></h2>
  <div class="row">

    <div class="col-md-12">
      <div class="card-container">
        <%= image_tag @celineversion.image, class: "card-container-img" %>
        <div class="card-container-infos">
          <h4>This CélineVersion was created by <strong><%= @celineversion.user.first_name.capitalize %> <%= @celineversion.user.last_name.capitalize %></strong></h4>
          <h2 class="mt-3"><strong>What is it about?</strong></h2>
          <h3 class="m-3"><%= @celineversion.description %></h3>
        </div>
        <div class="border-top border-dark m-4">
          <h3 class="m-3"><strong>Interested ?</strong> You can book this CélineVersion for just <strong><%= @celineversion.price %> $CAD per day.</strong></h3>
        </div>
        <div class="text-center">
          <ul>
            <%= link_to "BOOK THIS VERSION", new_celineversion_booking_path(@celineversion), { class: "btn btn-dark" } %>
            <% if @celineversion.user == current_user %>
              <%= link_to "EDIT", edit_celineversion_path(@celineversion), { class: "btn btn-outline-dark" } %>
              <%= link_to "DELETE", celineversion_path(@celineversion), method: :delete, data: {confirm: "Are you sure you want to drop this Céline?"}, class: "btn btn-outline-danger" %>
            <% end %>
          </ul>
        </div>
      </div>
    <div class="mt-5 text-right"><%= link_to "BACK TO ALL VERSIONS", celineversions_path, class: "btn btn-light active" %></div>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Book all the Céline of your dreams - CélineDnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="position: relative; min-height: 100vh;">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
  <footer>
    <%#= render 'shared/footer' %>
  </footer>
</html>

app/views/my_celineversions/index.html.erb
<div class="container">

  <% if @celineversions.length < 1 %>
  <div class="d-flex mt-4">
    <%= image_tag current_user.avatar, class: "avatar-profile mr-3" %>
    <div class="text-left">
      <h2><strong><%= current_user.first_name.capitalize %></strong>'s created CélineVersions & related bookings</h2>
      <h5 class="mb-5">You have no Céline version on your own yet</h5>
    </div>
  </div>
  <% else %>

     <div class="d-flex mt-4">
    <%= image_tag current_user.avatar, class: "avatar-profile mr-3" %>
    <div class="text-left">
      <h2><strong><%= current_user.first_name.capitalize %></strong>'s created CélineVersions & related bookings</h2>
      <h5 class="mb-5">Check your bookings below.</h5>
    </div>
  </div>
    <% @celineversions.each do |t| %>

      <div class="my-celines-card">
        <div class="card-celine-version">

      <!-- card-celine-version: Celine version and pic -->
      <!-- CODE START -->
        <div class="card-container my-celine-versions-card">
            <%= image_tag t.image, width: 300 %>
            <div class="card-container-infos">
              <h2 class="text-left"><%= t.name  %></h2>
              <h4 class="mt-3 text-justify"><%= t.description %></h4>
            </div>

            <div class="text-center mb-4">
              <!-- <h4 class="mb-2"><strong><%= t.price %> $CAD/day</strong></h4> -->
              <%#= link_to "CHECK THIS VERSION", celineversion_path(t), { class: "btn btn-outline-dark font-weight-bold" } %>
            </div>
          </div>
      <!-- CODE END -->
        </div>


        <div class="booking-container">
          <!-- booking-container -->
          <div class="booking-info-cards">
            <!-- booking-info-cards: Pending -->
            <!-- CODE START -->
            <h4><strong>Pending</strong></h4>
            <!-- CODE END -->

            <!-- CODE booking info loop pending START -->
            <% t.bookings.where(status: "Pending").reverse_each do |booking|  %>
              <div class="booking-info-card">
                <strong> <%= booking.user.full_name %></strong>
                <br>
                <%= booking.start_date %> <em>to</em> <%= booking.end_date %>
                <!-- booking-info-card -->
                <!-- buttons -->
                <div class="btn-container">
                  <%= simple_form_for(booking, defaults: { input_html: { class: 'default_class' } } ) do |f|  %>
                    <div class="booking-btn">
                      <%= f.input :status, as: :hidden, input_html: { value: "Confirmed" } %>
                      <%= f.submit("Confirm", { class: "btn btn-outline-success" }) %>
                    </div>
                  <% end %>
                  <%= simple_form_for(booking)  do |f|  %>
                    <div class="booking-btn">
                      <%= f.input :status, as: :hidden, input_html: { value: "Declined" } %>
                      <%= f.submit("Decline" , { class: "btn btn-outline-danger" }) %>
                    </div>
                  <% end %>
                  <button type="button" class="btn btn-outline-dark booking-btn" data-toggle="modal" data-target="#bookingModal-<%= booking.id %>">
                    Message
                  </button>
                  <!-- buttons end -->
                </div>
              </div>
            <% end %>
                      <!-- CODE booking info loop pending END -->

          </div>

          <div class="booking-info-cards">
            <!-- booking-info-cards: Confirmed -->
              <!-- CODE -->
              <h4><strong>Confirmed</strong></h4>
              <!-- CODE -->
              <% t.bookings.where(status: "Confirmed").reverse_each do |booking|  %>
            <div class="booking-info-card">
              <!-- booking-info-card -->
              <!-- CODE booking info loop confirmed START -->
              <strong><%= booking.user.full_name %></strong>
              <br>
              <%= booking.start_date %> <em>to</em> <%= booking.end_date %>
            </div>
              <% end %>
          </div>
        </div>
      </div>
      <% t.bookings.each do |booking| %>
        <%= render "shared/modal_booking_msg", booking: booking %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/my_celineversions/index_backup.html.erb
<div class="container">
  
  <% if @celineversions.length < 1 %>
    <h2 id=mycelineversion-h2>Your Célineversion's & related bookings</h2>
    <h5 >You have no Céline version on your own yet</h5>
  <% else %>

    <h2 id=mycelineversion-h2><strong>Your Célineversion's & related bookings</strong></h2>
    <% @celineversions.each do |t| %>

      <div class="my-celines-card">
        <div class="card-celine-version">
     
      <!-- card-celine-version: Celine version and pic -->
      <!-- CODE START -->
        <div class="card-container cc-hover mb-4">
            <%= image_tag t.image, width: 300 %>
            <div class="card-container-infos">
              <h2 class="text-left"><%= t.name  %></h2>
              <h4 class="mt-3 text-justify"><%= t.description %></h4>
            </div>

            <div class="text-center mb-4">
              <!-- <h4 class="mb-2"><strong><%= t.price %> $CAD/day</strong></h4> -->
              <%#= link_to "CHECK THIS VERSION", celineversion_path(t), { class: "btn btn-outline-dark font-weight-bold" } %>
            </div>
          </div>
      <!-- CODE END -->
        </div>


        <div class="booking-container">
          <!-- booking-container -->
          <div class="booking-info-cards">
            <!-- booking-info-cards: Pending -->
            <!-- CODE START -->
            <h4><strong>Pending</strong></h4>
            <!-- CODE END -->

            <!-- CODE booking info loop pending START -->
            <% t.bookings.where(status: "Pending").reverse_each do |booking|  %>
              <div class="booking-info-card">
                <strong> <%= booking.user.full_name %></strong>
                <br>
                <%= booking.start_date %> <em>to</em> <%= booking.end_date %>
                <!-- booking-info-card -->
                <!-- buttons -->
                <div class="btn-container">
                  <%= simple_form_for(booking, defaults: { input_html: { class: 'default_class' } } ) do |f|  %>
                    <div class="booking-btn">
                      <%= f.input :status, as: :hidden, input_html: { value: "Confirmed" } %>
                      <%= f.submit("Confirm", { class: "btn btn-outline-success" }) %>
                    </div>
                  <% end %>
                  <%= simple_form_for(booking)  do |f|  %>
                    <div class="booking-btn">
                      <%= f.input :status, as: :hidden, input_html: { value: "Declined" } %>
                      <%= f.submit("Decline" , { class: "btn btn-outline-danger" }) %>
                    </div>
                  <% end %>
                  <button type="button" class="btn btn-outline-dark booking-btn" data-toggle="modal" data-target="#bookingModal-<%= booking.id %>">
                    Message
                  </button>
                  <!-- buttons end -->
                </div>
              </div> 
            <% end %>
                      <!-- CODE booking info loop pending END -->

          </div>
          
          <div class="booking-info-cards">
            <!-- booking-info-cards: Confirmed -->
              <!-- CODE -->
              <h4><strong>Confirmed</strong></h4>
              <!-- CODE -->
              <% t.bookings.where(status: "Confirmed").reverse_each do |booking|  %>
            <div class="booking-info-card">
              <!-- booking-info-card -->
              <!-- CODE booking info loop confirmed START -->
              <strong><%= booking.user.full_name %></strong>
              <br>
              <%= booking.start_date %> <em>to</em> <%= booking.end_date %>


            </div> 
              <% end %>
          </div>
        </div>
      </div>
      <% t.bookings.each do |booking| %>
        <%= render "shared/modal_booking_msg", booking: booking %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="home-banner">
  <video id="VideoBackground" poster="https://meyersound.com/wp-content/uploads/2016/12/celine_dion_03.jpg" autoplay muted loop>
    <source src="https://res.cloudinary.com/dxnwiwjs5/video/upload/v1574454607/Celine_c67kic.mp4" type="video/mp4">
  </video>
    <div class="row justify-content-end">
      <div class="col-md-6 mt-5">
        <div class="card-wbody">
          <h3 class="card-title">Book the version of Céline Dion you always wanted to meet.</h3>
          <h5 class="card-text mt-4">Obviously, everyone is (secretely) a Céliner!</h5>
            <div class="card-section">
              <p class="text-headers-style"> You can list all the incredible CélineVersions we have!</p>
              <div class="card-section">
                <%= link_to "Display all CélineVersions", celineversions_path, { class: "btn btn-dark" } %>
              </div>
            </div>
            <div class="card-section">
              <p class="text-headers-style"> A CélineVersion is missing? We're waiting for you to add it!</p>
              <div class="card-section">
                <%= link_to "Create a new CélineVersion", new_celineversion_path, { class: "btn btn-dark" } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%#= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/celinedion/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/celinedion/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/celinedion"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <strong>CélineDnb </strong>was edited with <i class="fas fa-heart"></i> at Le Wagon Montréal - ⓒ 2019
  </div>
</div>

app/views/shared/_modal_booking_msg.html.erb
<!-- Modal -->
<div style="z-index:2000" class="modal fade" id="bookingModal-<%= booking.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Message from the Celiner</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= booking.message %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "CélineDnb", root_path, { class: "navbar-brand text-headers-style" } %>
<!--   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Display All CélineVersions", celineversions_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "View your bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Add a new CélineVersion", new_celineversion_path, class: "dropdown-item" %>
            <%= link_to "View your created CélineVersions", my_celineversions_path, class: "dropdown-item" %>
            <%= link_to "Edit your Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">

          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>